# Generated by Django 5.1.4 on 2025-01-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_carrating_comment_alter_carrating_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrating',
            name='user',
        ),
        migrations.AddField(
            model_name='carrating',
            name='rated_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
