# Generated by Django 5.1.4 on 2025-01-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carqrcode',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.car', unique=True),
        ),
    ]
