# Generated by Django 5.1.4 on 2025-01-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_carqrcode_car_alter_carqrcode_qrcode_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carqrcode',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.car'),
        ),
    ]
